name: Build eBrick

on:
  push:
    branches:
      - main          # Main branch
    paths-ignore:
      - '**/*.md'         # Ignore markdown files (documentation)
      - 'docs/**'         # Ignore the whole docs directory
      - 'README.md'       # Ignore README file
      - '.gitignore'      # Ignore .gitignore changes
      - '.editorconfig'   # Ignore editor configuration changes
      - '.vscode/**'      # Ignore VSCode specific files
      - '**/*.test'       # Ignore test output files
      - '**/*.log'        # Ignore log files
      - '**/*.txt'        # Ignore text files (if any)
      - 'vendor/**'       # Ignore vendor directory
      - 'LICENSE'         # Ignore license file
      - '.env'            # Ignore environment variable files
      - '.github/workflows/**'  # Ignore workflow changes if desired
      - 'bin/**'          # Ignore binary artifacts
      - 'dist/**'         # Ignore distribution artifacts

  pull_request:
    branches:
      - main          # Main branch
    paths-ignore:
      - '**/*.md'         # Ignore markdown files (documentation)
      - 'docs/**'         # Ignore the whole docs directory
      - 'README.md'       # Ignore README file
      - '.gitignore'      # Ignore .gitignore changes
      - '.editorconfig'   # Ignore editor configuration changes
      - '.vscode/**'      # Ignore VSCode specific files
      - '**/*.test'       # Ignore test output files
      - '**/*.log'        # Ignore log files
      - '**/*.txt'        # Ignore text files (if any)
      - 'vendor/**'       # Ignore vendor directory
      - 'LICENSE'         # Ignore license file
      - '.env'            # Ignore environment variable files
      - '.github/workflows/**'  # Ignore workflow changes if desired
      - 'bin/**'          # Ignore binary artifacts
      - 'dist/**'         # Ignore distribution artifacts
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'

      # Cache Go modules
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Install dependencies
      - name: Install dependencies
        run: go mod download

      # Run tests
      - name: Run tests
        run: go test -v ./...
